version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10
    - package-ecosystem: 'github-actions'
      # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory
      directory: '/'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 10
    - package-ecosystem: 'docker'
      directory: '/'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 10
