version: '3'
services:
    livekit:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nest-backend-template
        environment:
            - NODE_ENV=development
        networks:
            - dockernetwork
        depends_on:
            - postgres
        ports:
            - '3000:3000'
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_PORT: 5432
            POSTGRES_DB: doctor_care
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'

        networks:
            - dockernetwork
        restart: always

networks:
    dockernetwork:
        driver: bridge
