name: Deploy to Amazon ECR

on:
    push:
        branches:
            - gh-action
            - development
            - staging
            - production

env:
    AWS_REGION: ${{ secrets.LC_V2_VIDEO_CALL_AWS_REGION }} # set this to your preferred AWS region, e.g. us-west-1
    ECR_REPOSITORY: ${{ secrets.LC_V2_VIDEO_CALL_ECR_REGISTRY }} # set this to your Amazon ECR repository name

jobs:
    deploy:
        name: Deploy to Server
        runs-on: ubuntu-latest
        environment: development

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.LC_V2_VIDEO_CALL_AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.LC_V2_VIDEO_CALL_AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-southeast-2

            # - name: Login to Amazon ECR
            #   id: login-ecr
            #   uses: aws-actions/amazon-ecr-login@v2

            # - name: Build, tag, and push docker image to Amazon ECR
              # env:
              #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              #     REPOSITORY: repository-name
              # run: |
              #     docker build -t $REGISTRY/$REPOSITORY:${{ github.sha }} -t $REGISTRY/$REPOSITORY:latest .
              #     docker push --all-tags $REGISTRY/$REPOSITORY
