name: Release

on:
    push:
        branches:
            - development

jobs:
    release:
        name: Release
        permissions:
            contents: write
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.SEMANTIC_RELEASE_BOT }}
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: latest

            - name: Install dependences
              run: pnpm install --frozen-lockfile
            - name: Build project
              run: pnpm build
            - name: Create release
              run: pnpm semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GIT_AUTHOR_NAME: github-actions
                  GIT_AUTHOR_EMAIL: 44210433+github-actions@users.noreply.github.com
                  GIT_COMMITTER_NAME: github-actions
                  GIT_COMMITTER_EMAIL: 44210433+github-actions@users.noreply.github.com
